### ISSUE TITLE
AttributeError: 'itertools.islice' object has no attribute 'next'

### ISSUE THREAD

**Issue by anayrat** [Networks-Learning/stackexchange-dump-to-postgres#5]
I tried your tool but I have theses errors : 
python 2.7 :
```
python load_into_pg.py Users
  File "load_into_pg.py", line 105
    print ("Could not read from file {}.".format(dbFile), file=sys.stderr)
                                                              ^
SyntaxError: invalid syntax
```
python3:
```
python3 load_into_pg.py Users
This will drop the Users table. Are you sure [y/n]?y
Pre-processing ...
Pre-processing took 0.1 seconds
Processing data ...
Traceback (most recent call last):
  File "load_into_pg.py", line 274, in <module>
    handleTable(table, keys, args.dbname, args.file, args.host, args.port, args.username, args.password)
  File "load_into_pg.py", line 82, in handleTable
    for rows in Processor.batch(Processor.parse(xml), 500):
  File "/var/lib/postgresql/9.6/stack/python/stackexchange-dump-to-postgres/row_processor.py", line 34, in batch
    yield chain([batchiter.next()], batchiter)
AttributeError: 'itertools.islice' object has no attribute 'next'
```

I'm under debian jessie with virtualenv : 
```
pip freeze
argparse==1.2.1
lxml==3.4.1
psycopg2==2.5.4
wsgiref==0.1.2

```

**Comment by musically-ut** [comment]
I have just pushed a commit which ought to fix these errors using `six`. See if that helps with these compatibility woes.

Thanks for the report!

**Comment by anayrat** [comment]
It solves my issue. Thanks!
